apiVersion: v1
kind: ConfigMap
metadata:
  name: dmqtt-config
  namespace: dmqtt
  labels:
    app.kubernetes.io/name: dmqtt
data:
  DMQTT_TCP_ADDR: ":1883"
  DMQTT_HTTP_ADDR: ":9090"
  DMQTT_DATA_DIR: "/data/dmqtt"
  DMQTT_LOG_LEVEL: "info"
  DMQTT_CLUSTER_ENABLED: "true"
  DMQTT_CLUSTER_GOSSIP_PORT: "7000"
